def get_region_product_type_mapping() -> dict[str, dict[str, str]]:
    return {
        "France": {
            "Ensemble": "Ensemble",
            "Alimentation": "Alimentation",
            "Alimentation : Produits frais": "Produits frais",
            "Alimentation : Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
        "Guyane": {
            "Ensemble des produits": "Ensemble",
            "Alimentation": "Alimentation",
            "Produits frais": "Produits frais",
            "Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et Chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
        "Martinique": {
            "Ensemble des produits": "Ensemble",
            "Alimentation": "Alimentation",
            "Produits frais": "Produits frais",
            "Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et Chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
        "Guadeloupe": {
            "Ensemble des produits": "Ensemble",
            "Alimentation": "Alimentation",
            "Produits frais": "Produits frais",
            "Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et Chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
        "La Réunion": {
            "Ensemble des produits": "Ensemble",
            "Alimentation": "Alimentation",
            "Produits frais": "Produits frais",
            "Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et Chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
        "France Métropolitaine": {
            "Ensemble": "Ensemble",
            "Alimentation": "Alimentation",
            "Alimentation : Produits frais": "Produits frais",
            "Alimentation : Autres produits alimentaires": "Autre alimentation",
            "Tabac": "Tabac",
            "Produits manufacturés": "Produits manufacturés",
            "Produits manufacturés : Habillement et chaussures": "Habillement et chaussures",
            "Produits manufacturés : Produits de santé": "Produits de santé",
            "Autres produits manufacturés": "Autres produits manufacturés",
            "Énergie": "Énergie",
            "Énergie : Produits pétroliers": "dont Produits pétroliers",
            "Services": "Services",
            "Services : Loyers, eau et enlèvement des ordures ménagères": "Loyers, eau et enlèvement des ordures ménagères",
            "Services de santé": "Services de santé",
            "Services : Transports": "Transports",
            "Services : Communications": "Communications",
            "Autres services": "Autres services",
        },
    }
